import {Directive, ElementRef, HostListener, Input} from '@angular/core';
import {NgxEasilyDraggableService} from './ngx-easily-draggable.service';

/**
 * Directive that makes a DOM element draggable.
 */
@Directive({
  selector: '[ngxEasilyDraggable]'
})
export class NgxEasilyDraggableDirective {

  /**
   * Enable the drag image ("ghost") generated by the browser? Defaults to true. If set to false, does not render any drag image.
   */
  @Input() public enableDragImage = true;

  /**
   * Entity that's represented by the DOM element. Will be passed to (dropped) event listeners as
   * NgxEasilyDraggableDropElement.draggedElement.representing.
   */
  @Input() public representing: any = null;

  /**
   * How is the visual feedback supposed to look like that represents this operation?
   */
  @Input() dropEffect: 'copy' | 'move' | 'link' | 'none' = 'none';
  public dragImage: HTMLImageElement;

  constructor(private elementRef: ElementRef,
              private service: NgxEasilyDraggableService) {
    this.elementRef.nativeElement.draggable = 'true';
    if (!this.service.dragImage) {
      this.service.dragImage = document.createElement('img');
      this.service.dragImage.src = 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7'
      this.service.dragImage.style.width = '1px';
      this.service.dragImage.style.height = '1px';
    }
    document.body.appendChild(this.service.dragImage);
  }

  @HostListener('dragstart', ['$event'])
  public dragStart(event: DragEvent) {
    this.service.draggedElement = {
      elementRef: this.elementRef,
      representing: this.representing
    };
    if (!this.enableDragImage) {


      event.dataTransfer.setDragImage(this.service.dragImage, 0, 0);
    }
    event.dataTransfer.effectAllowed = this.dropEffect;
  }
}
